### ISSUE TITLE
Basic API specification

### ISSUE THREAD

**Issue by inureyes** [lablup/sorna-client#1]
- Basic API specification
- Requirements
  - [x] Authentication method
  - [x] Policy for anonymous users
  - [x] Specification
  - [x] REST API
  - [x] ~XML-RPC API?~
  - [x] GET / POST simple API (for traditional users?)
  - [x] WebSocket API for web terminals

**Comment by inureyes** [comment]
Each item can be an issue. Lets' branch them if discussion / sketch is finished here.

**Comment by achimnol** [comment]
Now we proceed to APIv2.
