### ISSUE TITLE
Provide shortcut / alias

### ISSUE THREAD

**Issue by inureyes** [lablup/sorna-client#8]
* Provide shortcut or aliases for intuitive understanding about the sorna system

### Suggestion
 * `lcc` : C/C++ on lablup.ai cloud.
 * `lpython` : python on lablup.ai cloud.

**Comment by achimnol** [comment]
We can do this using [entry points of the setup script](http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation). Wait a moment!
